# Generated by Django 3.0.5 on 2021-02-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_item',
            name='FoodItemID',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='rateID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='view_event',
            name='EventID',
        ),
    ]
